/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/link/runs/{run}/instructions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hold open the stream of instructions for a Run.
         * @description Replays every instruction after `Last-Event-ID`, then stays open. The stream closes when the Run ends.
         */
        get: operations["instructions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/link/runs/{run}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report something about an Environment to the control plane. */
        post: operations["report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description What the control plane asks of an Environment. */
        Instruction: components["schemas"]["Stop"];
        /** @description Leave the link and exit. */
        Stop: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "stop";
        };
        /** @description What an Environment tells the control plane about itself. */
        Report: components["schemas"]["Connected"];
        /** @description The Environment is on the link, and this is what is running in it. */
        Connected: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "connected";
            /** @description The supervisor's version. */
            version: string;
        };
        Refusal: {
            message: string;
        };
    };
    responses: {
        /** @description The link refused the request. */
        Refused: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Refusal"];
            };
        };
    };
    parameters: {
        /** @description The Run this Environment is executing. */
        run: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    instructions: {
        parameters: {
            query?: never;
            header?: {
                /** @description The seq of the last instruction this Environment received. Absent means from the beginning. */
                "Last-Event-ID"?: number;
            };
            path: {
                /** @description The Run this Environment is executing. */
                run: components["parameters"]["run"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stream is open. Each event carries an instruction as its data, the instruction's kind as its event name, and its seq as its id. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["Instruction"];
                };
            };
            401: components["responses"]["Refused"];
            403: components["responses"]["Refused"];
            404: components["responses"]["Refused"];
            503: components["responses"]["Refused"];
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Run this Environment is executing. */
                run: components["parameters"]["run"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Report"];
            };
        };
        responses: {
            /** @description The report was recorded. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Refused"];
            403: components["responses"]["Refused"];
            404: components["responses"]["Refused"];
            503: components["responses"]["Refused"];
        };
    };
}
